[package]
name = "liblokinet"
version = "0.1.0"
edition = "2021"
build="build.rs"

[build-dependencies]
cmake = "0.1.49"

[dependencies]
tokio = { version = "1", features = ["io-util", "sync", "rt-multi-thread", "net", "macros", "time"] }
